#import <PEGKit/PKParser.h>

enum {
    CREATETABLESTMT_TOKEN_KIND_NOT_UPPER = 14,
    CREATETABLESTMT_TOKEN_KIND_CREATE = 15,
    CREATETABLESTMT_TOKEN_KIND_EXISTS = 16,
    CREATETABLESTMT_TOKEN_KIND_TEMPORARY = 17,
    CREATETABLESTMT_TOKEN_KIND_TABLE = 18,
    CREATETABLESTMT_TOKEN_KIND_TEMP = 19,
    CREATETABLESTMT_TOKEN_KIND_IF = 20,
    CREATETABLESTMT_TOKEN_KIND_SEMI_COLON = 21,
};

@interface CreateTableStmtParser : PKParser

@end

