#import <PEGKit/PKParser.h>

enum {
    DUPELITERALS_TOKEN_KIND_NONE_1 = 14,
    DUPELITERALS_TOKEN_KIND_NONE_2,
    DUPELITERALS_TOKEN_KIND_PIPE,
    DUPELITERALS_TOKEN_KIND_NONE,
    DUPELITERALS_TOKEN_KIND_QUOTE,
};

@interface DupeLiteralsParser : PKParser

@end

