#import <PEGKit/PKParser.h>

enum {
    DUPELITERALS_DUPELITERALS_DUPELITERALS_TOKEN_KIND_NONE = 14,
    DUPELITERALS_DUPELITERALS_DUPELITERALS_TOKEN_KIND_NONE,
    DUPELITERALS_TOKEN_KIND_WEIRD,
    DUPELITERALS_DUPELITERALS_DUPELITERALS_TOKEN_KIND_NONE,
};

@interface DupeLiteralsParser : PKParser

@end

