#import <PEGKit/PKParser.h>

enum {
    DUPELITERALS_DUPELITERALS_DUPELITERALS_TOKEN_KIND_NONE = 14,
    DUPELITERALS_DUPELITERALS_DUPELITERALS_TOKEN_KIND_NONE,
    DUPELITERALS_TOKEN_KIND_1,
    DUPELITERALS_DUPELITERALS_DUPELITERALS_TOKEN_KIND_NONE,
    DUPELITERALS_TOKEN_KIND_2,
};

@interface DupeLiteralsParser : PKParser

@end

