#import <PEGKit/PKParser.h>

enum {
    DUPELITERALS_TOKEN_KIND_NONE_1 = 14,
    DUPELITERALS_TOKEN_KIND_NONE_2 = 15,
    DUPELITERALS_TOKEN_KIND_PIPE = 16,
    DUPELITERALS_TOKEN_KIND_NONE = 17,
    DUPELITERALS_TOKEN_KIND_QUOTE = 18,
};

@interface DupeLiteralsParser : PKParser

@end

