#import <PEGKit/PKParser.h>

enum {
    ELEMENTASSIGN_TOKEN_KIND_RBRACKET = 14,
    ELEMENTASSIGN_TOKEN_KIND_LBRACKET = 15,
    ELEMENTASSIGN_TOKEN_KIND_COMMA = 16,
    ELEMENTASSIGN_TOKEN_KIND_EQ = 17,
    ELEMENTASSIGN_TOKEN_KIND_SEMI = 18,
    ELEMENTASSIGN_TOKEN_KIND_DOT = 19,
};

@interface ElementAssignParser : PKParser

@end

