#import <PEGKit/PKParser.h>

enum {
    EXPRESSION_TOKEN_KIND_GE = 14,
    EXPRESSION_TOKEN_KIND_COMMA = 15,
    EXPRESSION_TOKEN_KIND_OR = 16,
    EXPRESSION_TOKEN_KIND_LT = 17,
    EXPRESSION_TOKEN_KIND_LE = 18,
    EXPRESSION_TOKEN_KIND_EQ = 19,
    EXPRESSION_TOKEN_KIND_DOT = 20,
    EXPRESSION_TOKEN_KIND_GT = 21,
    EXPRESSION_TOKEN_KIND_OPENPAREN = 22,
    EXPRESSION_TOKEN_KIND_YES = 23,
    EXPRESSION_TOKEN_KIND_NO = 24,
    EXPRESSION_TOKEN_KIND_CLOSEPAREN = 25,
    EXPRESSION_TOKEN_KIND_NE = 26,
    EXPRESSION_TOKEN_KIND_AND = 27,
};

@interface ExpressionParser : PKParser

@end

