#import <PEGKit/PKParser.h>

enum {
    EXPRESSIONACTIONS_TOKEN_KIND_NO = 14,
    EXPRESSIONACTIONS_TOKEN_KIND_NO_UPPER = 15,
    EXPRESSIONACTIONS_TOKEN_KIND_GE_SYM = 16,
    EXPRESSIONACTIONS_TOKEN_KIND_COMMA = 17,
    EXPRESSIONACTIONS_TOKEN_KIND_OR = 18,
    EXPRESSIONACTIONS_TOKEN_KIND_LT_SYM = 19,
    EXPRESSIONACTIONS_TOKEN_KIND_LE_SYM = 20,
    EXPRESSIONACTIONS_TOKEN_KIND_EQUALS = 21,
    EXPRESSIONACTIONS_TOKEN_KIND_DOT = 22,
    EXPRESSIONACTIONS_TOKEN_KIND_GT_SYM = 23,
    EXPRESSIONACTIONS_TOKEN_KIND_AND = 24,
    EXPRESSIONACTIONS_TOKEN_KIND_OPEN_PAREN = 25,
    EXPRESSIONACTIONS_TOKEN_KIND_YES = 26,
    EXPRESSIONACTIONS_TOKEN_KIND_CLOSE_PAREN = 27,
    EXPRESSIONACTIONS_TOKEN_KIND_NOT_EQUAL = 28,
    EXPRESSIONACTIONS_TOKEN_KIND_YES_UPPER = 29,
};

@interface ExpressionActionsParser : PKParser

@end

