#import <PEGKit/PKParser.h>

enum {
    HTML_TOKEN_KIND_SCRIPTTAGNAME = 14,
    HTML_TOKEN_KIND_STYLETAGNAME = 15,
    HTML_TOKEN_KIND_DOCTYPE = 16,
    HTML_TOKEN_KIND_LT = 17,
    HTML_TOKEN_KIND_PROCINSTR = 18,
    HTML_TOKEN_KIND_EQ = 19,
    HTML_TOKEN_KIND_FWDSLASH = 20,
    HTML_TOKEN_KIND_GT = 21,
};

@interface HTMLParser : PKParser

@end

