#import <PEGKit/PKParser.h>

enum {
    METHODSFACTORED_TOKEN_KIND_INT = 14,
    METHODSFACTORED_TOKEN_KIND_CLOSE_CURLY = 15,
    METHODSFACTORED_TOKEN_KIND_COMMA = 16,
    METHODSFACTORED_TOKEN_KIND_VOID = 17,
    METHODSFACTORED_TOKEN_KIND_OPEN_PAREN = 18,
    METHODSFACTORED_TOKEN_KIND_OPEN_CURLY = 19,
    METHODSFACTORED_TOKEN_KIND_CLOSE_PAREN = 20,
    METHODSFACTORED_TOKEN_KIND_SEMI_COLON = 21,
};

@interface MethodsFactoredParser : PKParser

@end

