// The MIT License (MIT)
//
// Copyright (c) 2014 Todd Ditchendorf
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

#import <PEGKit/PKParser.h>

enum {
    PEGKIT_TOKEN_KIND_SYMBOL_TITLE = 14,
    PEGKIT_TOKEN_KIND_SEMANTICPREDICATE,
    PEGKIT_TOKEN_KIND_PIPE,
    PEGKIT_TOKEN_KIND_AFTERKEY,
    PEGKIT_TOKEN_KIND_CLOSE_CURLY,
    PEGKIT_TOKEN_KIND_TILDE,
    PEGKIT_TOKEN_KIND_EMAIL_TITLE,
    PEGKIT_TOKEN_KIND_COMMENT_TITLE,
    PEGKIT_TOKEN_KIND_DISCARD,
    PEGKIT_TOKEN_KIND_NUMBER_TITLE,
    PEGKIT_TOKEN_KIND_ANY_TITLE,
    PEGKIT_TOKEN_KIND_SEMI_COLON,
    PEGKIT_TOKEN_KIND_S_TITLE,
    PEGKIT_TOKEN_KIND_ACTION,
    PEGKIT_TOKEN_KIND_EQUALS,
    PEGKIT_TOKEN_KIND_AMPERSAND,
    PEGKIT_TOKEN_KIND_PATTERNNOOPTS,
    PEGKIT_TOKEN_KIND_PHRASEQUESTION,
    PEGKIT_TOKEN_KIND_QUOTEDSTRING_TITLE,
    PEGKIT_TOKEN_KIND_OPEN_PAREN,
    PEGKIT_TOKEN_KIND_AT,
    PEGKIT_TOKEN_KIND_PATTERNIGNORECASE,
    PEGKIT_TOKEN_KIND_BEFOREKEY,
    PEGKIT_TOKEN_KIND_EOF_TITLE,
    PEGKIT_TOKEN_KIND_URL_TITLE,
    PEGKIT_TOKEN_KIND_CLOSE_PAREN,
    PEGKIT_TOKEN_KIND_PHRASESTAR,
    PEGKIT_TOKEN_KIND_EMPTY_TITLE,
    PEGKIT_TOKEN_KIND_PHRASEPLUS,
    PEGKIT_TOKEN_KIND_LETTER_TITLE,
    PEGKIT_TOKEN_KIND_OPEN_BRACKET,
    PEGKIT_TOKEN_KIND_COMMA,
    PEGKIT_TOKEN_KIND_SPECIFICCHAR_TITLE,
    PEGKIT_TOKEN_KIND_MINUS,
    PEGKIT_TOKEN_KIND_WORD_TITLE,
    PEGKIT_TOKEN_KIND_CLOSE_BRACKET,
    PEGKIT_TOKEN_KIND_CHAR_TITLE,
    PEGKIT_TOKEN_KIND_DIGIT_TITLE,
    PEGKIT_TOKEN_KIND_DELIMOPEN,
};

@interface PEGKitParser : PKParser

@end

